#version 450

layout(binding = 0, rgba8) uniform readonly image2D inputImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

// 32 x 32 = 1024, which appears to be the limit on my device
// (unclear if this is a standard or hardware specific)
layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

void main() {
    vec4 readPixel = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy));
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), readPixel);
}
