#version 450

layout(binding = 0, rgba8) uniform readonly image2D inputImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(local_size_x = 64, local_size_y = 64, local_size_z = 1) in;

void main() {
    vec3 readPixel = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy)).rgb;
    imageStore(outputImage, ivec2(gl_GlobalInvocationID.xy), vec4(vec3(1) - readPixel, 1.f));
}
